#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BindingLibTestApp.Resource", IsApplication=true)]

namespace BindingLibTestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int centered = 2130771974;
			
			// aapt resource value: 0x7f010011
			public const int clipPadding = 2130771985;
			
			// aapt resource value: 0x7f01001d
			public const int fadeDelay = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int fadeLength = 2130771998;
			
			// aapt resource value: 0x7f01001c
			public const int fades = 2130771996;
			
			// aapt resource value: 0x7f01000a
			public const int fillColor = 2130771978;
			
			// aapt resource value: 0x7f010012
			public const int footerColor = 2130771986;
			
			// aapt resource value: 0x7f010015
			public const int footerIndicatorHeight = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int footerIndicatorStyle = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int footerIndicatorUnderlinePadding = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int footerLineHeight = 2130771987;
			
			// aapt resource value: 0x7f010017
			public const int footerPadding = 2130771991;
			
			// aapt resource value: 0x7f010010
			public const int gapWidth = 2130771984;
			
			// aapt resource value: 0x7f010018
			public const int linePosition = 2130771992;
			
			// aapt resource value: 0x7f01000f
			public const int lineWidth = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int pageColor = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int radius = 2130771980;
			
			// aapt resource value: 0x7f010019
			public const int selectedBold = 2130771993;
			
			// aapt resource value: 0x7f010007
			public const int selectedColor = 2130771975;
			
			// aapt resource value: 0x7f01000d
			public const int snap = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int strokeColor = 2130771982;
			
			// aapt resource value: 0x7f010008
			public const int strokeWidth = 2130771976;
			
			// aapt resource value: 0x7f01001a
			public const int titlePadding = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int topPadding = 2130771995;
			
			// aapt resource value: 0x7f010009
			public const int unselectedColor = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int vpiIconPageIndicatorStyle = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int vpiLinePageIndicatorStyle = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int vpiTabPageIndicatorStyle = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int vpiTitlePageIndicatorStyle = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int vpiUnderlinePageIndicatorStyle = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_centered = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_circle_indicator_snap = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int default_line_indicator_centered = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int default_title_indicator_selected_bold = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int default_underline_indicator_fades = 2131165188;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int default_circle_indicator_fill_color = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int default_circle_indicator_page_color = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int default_circle_indicator_stroke_color = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int default_line_indicator_selected_color = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int default_line_indicator_unselected_color = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int default_title_indicator_footer_color = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int default_title_indicator_selected_color = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int default_title_indicator_text_color = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int default_underline_indicator_selected_color = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int vpi__background_holo_dark = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int vpi__background_holo_light = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int vpi__bright_foreground_disabled_holo_dark = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int vpi__bright_foreground_disabled_holo_light = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int vpi__bright_foreground_holo_dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int vpi__bright_foreground_holo_light = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int vpi__bright_foreground_inverse_holo_dark = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int vpi__bright_foreground_inverse_holo_light = 2131099655;
			
			// aapt resource value: 0x7f060011
			public const int vpi__dark_theme = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int vpi__light_theme = 2131099666;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_radius = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_circle_indicator_stroke_width = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int default_line_indicator_gap_width = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int default_line_indicator_line_width = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int default_line_indicator_stroke_width = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int default_title_indicator_clip_padding = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int default_title_indicator_footer_indicator_height = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int default_title_indicator_footer_indicator_underline_padding = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int default_title_indicator_footer_line_height = 2131296262;
			
			// aapt resource value: 0x7f090009
			public const int default_title_indicator_footer_padding = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int default_title_indicator_text_size = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int default_title_indicator_title_padding = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int default_title_indicator_top_padding = 2131296268;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int vpi__tab_indicator = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int vpi__tab_selected_focused_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int vpi__tab_selected_holo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int vpi__tab_selected_pressed_holo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int vpi__tab_unselected_focused_holo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int vpi__tab_unselected_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int vpi__tab_unselected_pressed_holo = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0003
			public const int bottom = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int circleIndicator = 2131361798;
			
			// aapt resource value: 0x7f0a0000
			public const int none = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int pager = 2131361799;
			
			// aapt resource value: 0x7f0a0005
			public const int titleIndicator = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int top = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public const int triangle = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int underline = 2131361794;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_orientation = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_title_indicator_footer_indicator_style = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int default_title_indicator_line_position = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int default_underline_indicator_fade_delay = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int default_underline_indicator_fade_length = 2131230724;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int TextAppearance_TabPageIndicator = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int Theme_PageIndicatorDefaults = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Widget = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int Widget_IconPageIndicator = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int Widget_TabPageIndicator = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					16842948,
					16842964,
					2130771974,
					2130771976,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public const int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_fillColor = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_pageColor = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_radius = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_snap = 7;
			
			// aapt resource value: 8
			public const int CirclePageIndicator_strokeColor = 8;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_strokeWidth = 3;
			
			public static int[] LinePageIndicator = new int[] {
					16842964,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771983,
					2130771984};
			
			// aapt resource value: 0
			public const int LinePageIndicator_android_background = 0;
			
			// aapt resource value: 1
			public const int LinePageIndicator_centered = 1;
			
			// aapt resource value: 6
			public const int LinePageIndicator_gapWidth = 6;
			
			// aapt resource value: 5
			public const int LinePageIndicator_lineWidth = 5;
			
			// aapt resource value: 2
			public const int LinePageIndicator_selectedColor = 2;
			
			// aapt resource value: 3
			public const int LinePageIndicator_strokeWidth = 3;
			
			// aapt resource value: 4
			public const int LinePageIndicator_unselectedColor = 4;
			
			public static int[] TitlePageIndicator = new int[] {
					16842901,
					16842904,
					16842964,
					2130771975,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995};
			
			// aapt resource value: 2
			public const int TitlePageIndicator_android_background = 2;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_android_textColor = 1;
			
			// aapt resource value: 0
			public const int TitlePageIndicator_android_textSize = 0;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_clipPadding = 4;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerColor = 5;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_footerIndicatorHeight = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_footerIndicatorStyle = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerLineHeight = 6;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_footerPadding = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_linePosition = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_selectedBold = 12;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_selectedColor = 3;
			
			// aapt resource value: 13
			public const int TitlePageIndicator_titlePadding = 13;
			
			// aapt resource value: 14
			public const int TitlePageIndicator_topPadding = 14;
			
			public static int[] UnderlinePageIndicator = new int[] {
					16842964,
					2130771975,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 0
			public const int UnderlinePageIndicator_android_background = 0;
			
			// aapt resource value: 3
			public const int UnderlinePageIndicator_fadeDelay = 3;
			
			// aapt resource value: 4
			public const int UnderlinePageIndicator_fadeLength = 4;
			
			// aapt resource value: 2
			public const int UnderlinePageIndicator_fades = 2;
			
			// aapt resource value: 1
			public const int UnderlinePageIndicator_selectedColor = 1;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
			
			// aapt resource value: 4
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
